$script:ScrubStr = @{
    # Header
    APP_NAME        = "Scrub"
    APP_TAGLINE     = "Windows Disk Maintenance"

    # Common
    LOADING         = "loading..."
    BACK            = "back"
    CANCEL          = "cancel"
    SAVE            = "save"
    TOGGLE          = "toggle"
    CHOOSE          = "Choose"
    NUM             = "Number"
    DAYS            = "days"
    PRESS_ENTER     = "Press Enter to go back"
    PRESS_ENTER_MENU= "Press Enter to go back to menu"
    CANCELED        = "Canceled."
    SAVED           = "Settings saved."
    NOT_FOUND       = "Path not found."
    CONFIRM_LIVE    = "LIVE mode will permanently delete files. Type '{0}' to confirm"
    CONFIRM_WORD    = "yes"
    CONFIRM_ACT     = "confirm"
    ABORTED         = "Aborted."
    DAYS_AGO_H      = "{0}h ago"
    DAYS_AGO_D      = "{0}d ago"
    NEVER           = "never"
    NEVER_RUN       = "never run"
    NEXT_IN         = "next in:"
    LAST_RUN        = "last:"

    # Main menu
    MENU_SCORE      = "Score:"
    MENU_PRESET     = "Preset:"
    MENU_P_TOGGLE   = "P = switch"
    MENU_1          = "[1]  Smart routine         "
    MENU_1_DESC     = "runs only what is needed, estimates time"
    MENU_2          = "[2]  Full routine           "
    MENU_2_DESC     = "dry-run -- analyzes, deletes nothing"
    MENU_3          = "[3]  Full routine LIVE      "
    MENU_3_DESC     = "actually deletes (asks for confirmation)"
    MENU_4          = "[4]  Specific routine       "
    MENU_4_DESC     = "choose which modules to run"
    MENU_5          = "[5]  Diagnose               "
    MENU_5_DESC     = "disk, health, logs and startup (read-only)"
    MENU_6          = "[6]  Manage startup          "
    MENU_6_DESC     = "enable/disable startup entries"
    MENU_7          = "[7]  Folder analyzer        "
    MENU_7_DESC     = "interactive disk usage explorer"
    MENU_8          = "[8]  History                "
    MENU_8_DESC     = "progress charts and score over time"
    MENU_9          = "[9]  Configure modules      "
    MENU_9_DESC     = "enable/disable, frequency and estimated time"
    MENU_A          = "[A]  Schedule daily run"
    MENU_B          = "[B]  Uninstall"
    MENU_0          = "[0]  Exit"
    MENU_I          = "[I]  Idioma / Language      "
    MENU_I_DESC     = "switch between Portuguese and English"

    # Smart routine
    SMART_TITLE     = "Smart Routine"
    SMART_ALL_DONE  = "All modules are up to date."
    SMART_LAST_RPT  = "Latest report:"
    SMART_READY     = "Modules ready to run:"
    SMART_FORCED    = "Forced re-run -- all enabled modules will run."
    SMART_SKIP      = "Up to date, will be skipped: {0} module(s)"
    SMART_EST       = "Time estimate:"
    SMART_LONG_WARN = "Warning: some steps may take over 20 minutes."
    SMART_V         = "view report"
    SMART_R         = "force re-run"
    SMART_E         = "dry-run"
    SMART_L         = "LIVE"

    # Module selector
    MOD_TITLE       = "Select modules:"
    MOD_ALWAYS      = "(Disk and disk health always run)"
    MOD_ALL         = "mark all"
    MOD_NONE        = "unmark all"
    MOD_EST         = "est:"
    MOD_UNSAVED     = "Unsaved changes. Exit? (y/N)"
    MOD_RUN_NOW     = "save & run"

    # Frequencies
    FREQ_DAILY      = "daily"
    FREQ_WEEKLY     = "weekly"
    FREQ_MONTHLY    = "monthly"
    FREQ_BIANNUAL   = "biannual"

    # Config
    CFG_MOD_TITLE   = "Configure modules  "
    CFG_MOD_SUB     = "(changes saved to config.json)"
    CFG_MOD_ALWAYS  = "Always active: Disk, Health Check, Pending Reboot"
    CFG_FREQ_TITLE  = "Frequency and estimated time"
    CFG_FREQ_DESC   = "(defines when each module is 'due' in the smart routine)"
    CFG_FREQ_DEFS   = "Default frequencies: 1=daily  7=weekly  30=monthly  180=biannual"
    CFG_EDITING     = "Editing:"
    CFG_FREQ_CUR    = "Current frequency:"
    CFG_FREQ_NEW    = "New frequency in days (1/7/30/180 or any number)"
    CFG_EST_CUR     = "Current estimated time:"
    CFG_EST_NEW     = "New time in seconds (Enter = keep)"
    CFG_NUM_EDIT    = "Number = edit"
    CFG_F_FREQ      = "frequency/time"
    CFG_CAUTION     = "[!] = caution"
    CFG_CAUTION_LBL = "caution"

    # Specific mode
    SPEC_DRY        = "[D]  Dry-run  (analyze only, no deletes)"
    SPEC_LIVE       = "[L]  LIVE     (actually deletes)"
    SPEC_CANCEL     = "[C]  Cancel"
    SPEC_MODE       = "Mode [D/L/C]"
    SPEC_CANCEL_CHR = "C"

    # Drive picker
    DRV_TITLE       = "Select drive..."
    DRV_FREE_OF     = "free of"

    # Folder analyzer
    FOLD_TITLE      = "Folder Analyzer"
    FOLD_TOTAL      = "total:"
    FOLD_UP         = "up"
    FOLD_NEXT       = "next"
    FOLD_PREV       = "prev"
    FOLD_PATH       = "path"
    FOLD_PATH_PROMPT= "Path"
    FOLD_ENTER      = "enter"
    FOLD_PROFILE    = "User profile"
    FOLD_DRIVE      = "Select drive"
    FOLD_TYPE_PATH  = "Type path"
    FOLD_CHECKING   = "checking"

    # History
    HIST_TITLE      = "History & Progress"
    HIST_MEASURES   = "measurements"
    HIST_FREE       = "Free space C: (GB) -- last {0} runs"
    HIST_FREED      = "Freed per run -- last {0} runs"
    HIST_NO_DATA    = "No data found."
    HIST_NO_DATA2   = "Run at least one routine to generate history."

    # Watch mode
    WATCH_TITLE     = "Scrub Watch"
    WATCH_STARTED   = "Watch mode started. Updating every {0}s. Ctrl+C to exit."
    WATCH_USED      = "used"
    WATCH_FREE_GB   = "GB free"
    WATCH_PENDING   = "PENDING"
    WATCH_LAST      = "Last run:"
    WATCH_UPDATE    = "Updating every {0}s"
    WATCH_EXIT      = "to exit"

    # Startup manager
    START_TITLE     = "Manage Startup"
    START_LOADING   = "Loading entries..."
    START_NONE      = "No entries found."
    START_NAV       = "Number = enable/disable   ok = exit"
    START_ENTRIES   = "entries"
    START_NAME      = "Name"
    START_TYPE      = "Type"
    START_SCOPE     = "Scope"
    START_CMD       = "Command"
    START_LOC       = "Location"
    START_DETAIL    = "details"
    START_DISABLE   = "Disable '{0}'?"
    START_ENABLE    = "Enable '{0}'?"

    # Scheduling
    SCHED_CURRENT   = "Current task:"
    SCHED_STATUS    = "Status:"
    SCHED_NEXT_RUN  = "Next:"
    SCHED_REMOVE    = "Remove schedule"
    SCHED_REMOVED   = "Schedule removed."
    SCHED_CREATE    = "Create daily scheduled task (auto dry-run, generates report)."
    SCHED_HINT      = "For real cleanup, keep running LIVE mode manually."
    SCHED_TIME_PROMPT = "Execution time (HH:mm, e.g. 09:00)"
    SCHED_TIME_ERR  = "Invalid format. Use HH:mm"
    SCHED_OK        = "Scheduled: every day at {0} (dry-run, report saved in reports\)"
    SCHED_FAIL      = "Failed:"

    # Run summary
    SUM_TITLE       = "Summary"
    SUM_FREED       = "freed"
    SUM_POTENTIAL   = "would free"
    SUM_TOTAL       = "Total:"
    SUM_NOTHING     = "--"

    # Preset manager
    PRESET_TITLE    = "Manage presets"
    PRESET_ACTIVE   = "active:"
    PRESET_BUILTIN  = "(built-in)"
    PRESET_SAVE_NEW = "save as new preset"
    PRESET_NAME_P   = "Preset name"
    PRESET_EXISTS   = "Name already in use."
    PRESET_EMPTY    = "No modules selected."
    PRESET_SAVED    = "Preset saved."
    PRESET_DELETED  = "Preset deleted."
    PRESET_LOADED   = "Preset activated."
    PRESET_CANT_DEL = "Cannot delete built-in presets."
    PRESET_MANAGE   = "presets"

    # Module config extras
    MOD_RESET       = "reset"

    # Uninstall
    UNINSTALL_CONFIRM = "Remove Scrub from PATH, Start Menu and PS module?"
    UNINSTALL_EXIT  = "Press Enter to exit"

    # Language
    LANG_SWITCHED   = "Language switched to English."
    LANG_NAME       = "English"
}
