$script:ScrubStr = @{
    # Cabecalho
    APP_NAME        = "Scrub"
    APP_TAGLINE     = "Manutencao de disco para Windows"

    # Comuns
    LOADING         = "carregando..."
    BACK            = "voltar"
    CANCEL          = "cancelar"
    SAVE            = "salvar"
    TOGGLE          = "alternar"
    CHOOSE          = "Escolha"
    NUM             = "Numero"
    DAYS            = "dias"
    PRESS_ENTER     = "Pressione Enter para voltar"
    PRESS_ENTER_MENU= "Pressione Enter para voltar ao menu"
    CANCELED        = "Cancelado."
    SAVED           = "Configuracao salva."
    NOT_FOUND       = "Caminho nao encontrado."
    CONFIRM_LIVE    = "LIVE mode apagara arquivos permanentemente. Digite '{0}' para confirmar"
    CONFIRM_WORD    = "sim"
    CONFIRM_ACT     = "confirmar"
    ABORTED         = "Abortado."
    DAYS_AGO_H      = "{0}h atras"
    DAYS_AGO_D      = "{0}d atras"
    NEVER           = "nunca"
    NEVER_RUN       = "nunca executado"
    NEXT_IN         = "proxima em:"
    LAST_RUN        = "ultima:"

    # Menu principal
    MENU_SCORE      = "Score:"
    MENU_PRESET     = "Preset:"
    MENU_P_TOGGLE   = "P = alternar"
    MENU_1          = "[1]  Rotina inteligente   "
    MENU_1_DESC     = "roda so o que e necessario, estima o tempo"
    MENU_2          = "[2]  Rotina completa       "
    MENU_2_DESC     = "dry-run -- analisa, nao deleta nada"
    MENU_3          = "[3]  Rotina completa LIVE  "
    MENU_3_DESC     = "deleta de verdade (pede confirmacao)"
    MENU_4          = "[4]  Rotina especifica      "
    MENU_4_DESC     = "escolha quais modulos rodar"
    MENU_5          = "[5]  Diagnosticar           "
    MENU_5_DESC     = "disco, saude, logs e inicializacao (so leitura)"
    MENU_6          = "[6]  Gerenciar startup       "
    MENU_6_DESC     = "ativar/desativar entradas de inicializacao"
    MENU_7          = "[7]  Analisar pasta          "
    MENU_7_DESC     = "uso de espaco interativo"
    MENU_8          = "[8]  Historico               "
    MENU_8_DESC     = "graficos de progresso e score ao longo do tempo"
    MENU_9          = "[9]  Configurar modulos     "
    MENU_9_DESC     = "ativar/desativar, frequencia e tempo estimado"
    MENU_A          = "[A]  Agendar execucao diaria"
    MENU_B          = "[B]  Desinstalar"
    MENU_0          = "[0]  Sair"
    MENU_I          = "[I]  Idioma / Language      "
    MENU_I_DESC     = "alternar entre portugues e ingles"

    # Rotina inteligente
    SMART_TITLE     = "Rotina Inteligente"
    SMART_ALL_DONE  = "Todos os modulos estao em dia."
    SMART_LAST_RPT  = "Ultimo relatorio:"
    SMART_READY     = "Modulos prontos para rodar:"
    SMART_FORCED    = "Re-execucao forcada -- todos os modulos habilitados serao rodados."
    SMART_SKIP      = "Em dia, serao pulados: {0} modulo(s)"
    SMART_EST       = "Estimativa de tempo:"
    SMART_LONG_WARN = "Aviso: algumas etapas podem levar mais de 20 minutos."
    SMART_V         = "ver relatorio"
    SMART_R         = "forcar re-execucao"
    SMART_E         = "dry-run"
    SMART_L         = "LIVE"

    # Seletor de modulos
    MOD_TITLE       = "Selecione os modulos:"
    MOD_ALWAYS      = "(Disco e saude do disco sempre rodam)"
    MOD_ALL         = "marcar todos"
    MOD_NONE        = "desmarcar todos"
    MOD_EST         = "est:"
    MOD_UNSAVED     = "Alteracoes nao salvas. Sair? (s/N)"
    MOD_RUN_NOW     = "salvar e executar"

    # Frequencias
    FREQ_DAILY      = "diario"
    FREQ_WEEKLY     = "semanal"
    FREQ_MONTHLY    = "mensal"
    FREQ_BIANNUAL   = "semestral"

    # Configuracao
    CFG_MOD_TITLE   = "Configurar modulos  "
    CFG_MOD_SUB     = "(alteracoes salvas em config.json)"
    CFG_MOD_ALWAYS  = "Sempre ativos: Disco, Health Check, Pending Reboot"
    CFG_FREQ_TITLE  = "Frequencia e tempo estimado"
    CFG_FREQ_DESC   = "(define quando cada modulo e 'devido' na rotina inteligente)"
    CFG_FREQ_DEFS   = "Frequencias padrao: 1=diario  7=semanal  30=mensal  180=semestral"
    CFG_EDITING     = "Editando:"
    CFG_FREQ_CUR    = "Frequencia atual:"
    CFG_FREQ_NEW    = "Nova frequencia em dias (1/7/30/180 ou qualquer numero)"
    CFG_EST_CUR     = "Tempo estimado atual:"
    CFG_EST_NEW     = "Novo tempo em segundos (Enter = manter)"
    CFG_NUM_EDIT    = "Numero = editar"
    CFG_F_FREQ      = "frequencia/tempo"
    CFG_CAUTION     = "[!] = cuidado"
    CFG_CAUTION_LBL = "cuidado"

    # Modo especifico
    SPEC_DRY        = "[D]  Dry-run  (so analisa, nao deleta)"
    SPEC_LIVE       = "[L]  LIVE     (deleta de verdade)"
    SPEC_CANCEL     = "[C]  Cancelar"
    SPEC_MODE       = "Modo [D/L/C]"
    SPEC_CANCEL_CHR = "C"

    # Drive picker
    DRV_TITLE       = "Selecionar drive..."
    DRV_FREE_OF     = "livre de"

    # Analisador de pastas
    FOLD_TITLE      = "Analisar Pasta"
    FOLD_TOTAL      = "total:"
    FOLD_UP         = "subir"
    FOLD_NEXT       = "prox"
    FOLD_PREV       = "ant"
    FOLD_PATH       = "caminho"
    FOLD_PATH_PROMPT= "Caminho"
    FOLD_ENTER      = "entrar"
    FOLD_PROFILE    = "Perfil do usuario"
    FOLD_DRIVE      = "Selecionar drive"
    FOLD_TYPE_PATH  = "Digitar caminho"
    FOLD_CHECKING   = "verificando"

    # Historico
    HIST_TITLE      = "Historico & Progresso"
    HIST_MEASURES   = "medicoes"
    HIST_FREE       = "Espaco livre C: (GB) -- ultimas {0} execucoes"
    HIST_FREED      = "Liberado por execucao -- ultimas {0} execucoes"
    HIST_NO_DATA    = "Nenhum dado encontrado."
    HIST_NO_DATA2   = "Execute pelo menos uma rotina para gerar historico."

    # Startup manager
    START_TITLE     = "Gerenciar Startup"
    START_LOADING   = "Carregando entradas..."
    START_NONE      = "Nenhuma entrada encontrada."
    START_NAV       = "Numero = ativar/desativar   ok = sair"
    START_ENTRIES   = "entradas"
    START_NAME      = "Nome"
    START_TYPE      = "Tipo"
    START_SCOPE     = "Escopo"
    START_CMD       = "Comando"
    START_LOC       = "Local"
    START_DETAIL    = "detalhes"
    START_DISABLE   = "Desabilitar '{0}'?"
    START_ENABLE    = "Habilitar '{0}'?"

    # Agendamento
    SCHED_CURRENT   = "Tarefa atual:"
    SCHED_STATUS    = "Status:"
    SCHED_NEXT_RUN  = "Proximo:"
    SCHED_REMOVE    = "Remover agendamento"
    SCHED_REMOVED   = "Agendamento removido."
    SCHED_CREATE    = "Criar tarefa agendada diaria (dry-run automatico, gera relatorio)."
    SCHED_HINT      = "Para limpeza real, continue rodando o modo LIVE manualmente."
    SCHED_TIME_PROMPT = "Horario de execucao (HH:mm, ex: 09:00)"
    SCHED_TIME_ERR  = "Formato invalido. Use HH:mm"
    SCHED_OK        = "Agendado: todo dia as {0} (dry-run, relatorio gerado em reports\)"
    SCHED_FAIL      = "Falha:"

    # Resumo da execucao
    SUM_TITLE       = "Resumo"
    SUM_FREED       = "liberado"
    SUM_POTENTIAL   = "liberaria"
    SUM_TOTAL       = "Total:"
    SUM_NOTHING     = "--"

    # Gerenciar presets
    PRESET_TITLE    = "Gerenciar presets"
    PRESET_ACTIVE   = "ativo:"
    PRESET_BUILTIN  = "(embutido)"
    PRESET_SAVE_NEW = "salvar como novo preset"
    PRESET_NAME_P   = "Nome do preset"
    PRESET_EXISTS   = "Nome ja em uso."
    PRESET_EMPTY    = "Nenhum modulo selecionado."
    PRESET_SAVED    = "Preset salvo."
    PRESET_DELETED  = "Preset removido."
    PRESET_LOADED   = "Preset ativado."
    PRESET_CANT_DEL = "Presets embutidos nao podem ser removidos."
    PRESET_MANAGE   = "presets"

    # Extras de configuracao de modulos
    MOD_RESET       = "resetar"

    # Desinstalar
    UNINSTALL_CONFIRM = "Remover Scrub do PATH, Start Menu e modulo PS?"
    UNINSTALL_EXIT  = "Pressione Enter para sair"

    # Painel de diagnostico
    DIAG_TITLE      = "Diagnostico"
    DIAG_DISK_SPACE = "Espaco em disco (C:)"
    DIAG_DISK_HEALTH= "Saude do disco (SMART)"
    DIAG_REBOOT     = "Reboot pendente"
    DIAG_REBOOT_YES = "reboot necessario"
    DIAG_REBOOT_NO  = "nao necessario"
    DIAG_EVENT_LOG  = "Erros no Event Log (24h)"
    DIAG_DRIVERS    = "Drivers"
    DIAG_STARTUP    = "Entradas de startup"
    DIAG_UPDATES    = "Windows Updates"
    DIAG_SCORE      = "Health Score"
    DIAG_FREE       = "livre"
    DIAG_USED       = "usado"
    DIAG_DISKS      = "disco(s)"
    DIAG_DEVICES    = "dispositivo(s)"
    DIAG_ENTRIES    = "entradas"
    DIAG_ERRORS     = "erro(s)"
    DIAG_NO_ERRORS  = "sem erros"
    DIAG_PROBLEMS   = "problematico(s)"
    DIAG_PENDING    = "pendente(s)"
    DIAG_UP_TO_DATE = "em dia"
    DIAG_UPDATE_ERR = "verificacao falhou"

    # Idioma
    LANG_SWITCHED   = "Idioma alterado para Portugues."
    LANG_NAME       = "Portugues"
}
